[package]
name = "day09"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[[bin]]
name="day09-part1"
path="src/bin/part1.rs"
[[bin]]
name="day09-part2"
path="src/bin/part2.rs"
